name: Build

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      build:
        type: string
        required: true
      repo_owner:
        type: string
        required: true
      repo_name:
        type: string
        required: true
    secrets:
      pat:
        required: true

jobs:
  build:
    runs-on: windows-latest
    if: ${{ inputs.build == 'true' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          token: ${{ secrets.pat }}

      - name: Setup Java
        if: ${{ inputs.stack == 'JAVA SPRINGBOOT' || inputs.stack == 'JAVA MAVEN' }}
        uses: actions/setup-java@v2
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "8"

      - name: Test Java Spring Boot Application
        if: inputs.stack == 'JAVA SPRINGBOOT'
        run: |
          echo "Running tests from JAVA SPRINGBOOT"
          mvn clean package -DskipTests=true

      - name: Test Java Maven Application
        if: inputs.stack == 'JAVA MAVEN'
        run: |
          echo "Running tests from JAVA MAVEN"
          mvn clean package -DskipTests=true
