name: Build

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      build:
        type: string
        required: true
      repo_owner:
        type: string
        required: true
      repo_name:
        type: string
        required: true
      pat:
        type: string
        required: true
        description: Personal Access Token (PAT)
    #secrets:
    #  my_pat:
    #    required: true

jobs:
  # JAVA SPRINGBOOT STACK

  build_java_spring:
    runs-on: windows-latest
    if: ${{ inputs.build == 'true' && inputs.stack == 'JAVA SPRINGBOOT' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          token: ${{ inputs.pat }}

      #its possible to use a shell script to run the build
      - run: |
          echo "Running build from JAVA SPRINGBOOT"
          ls -la

  # JAVA MAVEN STACK

  build_java_maven:
    runs-on: windows-latest
    if: ${{ inputs.build == 'true' && inputs.stack == 'JAVA MAVEN' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          token: ${{ inputs.pat }}

      #its possible to use a shell script to run the build
      - run: |
          echo "Running build from JAVA MAVEN"
          ls -la
