name: Publish

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      publish:
        type: string
        required: true
      repo_owner:
        type: string
        required: true
      repo_name:
        type: string
        required: true
    secrets:
      pat:
        required: true

#github.run_number can be used to identify the run number

jobs:
  publish:
    runs-on: windows-latest
    if: ${{ inputs.publish == 'true' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Get build artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ inputs.repo_name }}-${{ github.run_number }}
          path: build

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ inputs.repo_name }}-${{ github.run_number }}
          tag_name: ${{ inputs.repo_name }}-${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            build/*.jar
