name: Publish

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      publish:
        type: string
        required: true
      repo_onwer:
        type: string
        required: true
      repo_name:
        type: string
        required: true
    secrets:
      my_pat:
        required: true

jobs:
  # JAVA SPRINGBOOT STACK

  publish_java_spring:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish == 'true' && inputs.stack == 'JAVA SPRINGBOOT' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          token: ${{ secrets.my_pat }}

      #its possible to use a shell script to run the tests
      - run: |
          echo "Running publish from JAVA SPRINGBOOT"
          ls -la

  # JAVA MAVEN STACK

  publish_java_maven:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish == 'true' && inputs.stack == 'JAVA MAVEN' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          token: ${{ secrets.my_pat }}

      #its possible to use a shell script to run the tests
      - run: |
          echo "Running publish from JAVA MAVEN"
          ls -la
