name: Publish

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      publish:
        type: string
        required: true
  #  secrets:
  #    token:
  #      required: true

jobs:

 ###############################################################################

  publish_java_spring:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish == 'true' && inputs.stack == 'JAVA SPRINGBOOT' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ secrets.my_pat }}
      
      #its possible to use a shell script to run the tests
      - run: |
        echo "Running publish from JAVA SPRINGBOOT"
        ls -la

###############################################################################

  publish_java_quarkus:
    runs-on: ubuntu-latest
    if: ${{ inputs.publish == 'true' && inputs.stack == 'JAVA QUARKUS' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ secrets.my_pat }}
      
      #its possible to use a shell script to run the tests
      - run: |
        echo "Running publish from JAVA QUARKUS"
        ls -la

###############################################################################
