name: Start

on:
  workflow_dispatch:
    inputs:
      repo:
        description: Target repository
        required: true
      stack:
        type: choice
        description: Choose a language stack
        options:
          - JAVA SPRINGBOOT
          - JAVA QUARKUS
      tests:
        type: boolean
        description: Unit tests?
        default: true
      build:
        type: boolean
        description: Build? [depends on tests]
        default: true
      publish:
        type: boolean
        description: Publish? [depends on build]
        default: true

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Show options
        run: |
          echo "   REPO: ${{ github.event.inputs.repo }}"
          echo "  STACK: ${{ github.event.inputs.stack }}"
          echo "  TESTS: ${{ github.event.inputs.tests }}"
          echo "  BUILD: ${{ github.event.inputs.build }}"
          echo "PUBLISH: ${{ github.event.inputs.publish }}"

  tests:
    needs:
      - start
    if: ${{ github.event.inputs.tests == 'true'}}
    uses: eduardomp/dynamic-gh-workflows/.github/workflows/tests.yml@main
    with:
      tests: ${{ github.event.inputs.tests }}
      stack: ${{ github.event.inputs.stack }}
    secrets:
      my_pat: ${{ secrets.my_pat }}

  build:
    needs:
      - tests
    if: ${{ github.event.inputs.build == 'true'}}
    uses: eduardomp/dynamic-gh-workflows/.github/workflows/build.yml@main
    with:
      build: ${{ github.event.inputs.build }}
      stack: ${{ github.event.inputs.stack }}
    secrets:
      my_pat: ${{ secrets.my_pat }}

  publish:
    needs:
      - build
    if: ${{ github.event.inputs.publish == 'true'}}
    uses: eduardomp/dynamic-gh-workflows/.github/workflows/publish.yml@main
    with:
      publish: ${{ github.event.inputs.publish }}
      stack: ${{ github.event.inputs.stack }}
    secrets:
      my_pat: ${{ secrets.my_pat }}
