name: Tests

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      tests:
        type: string
        required: true
      repo_owner:
        type: string
        required: true
      repo_name:
        type: string
        required: true
    secrets:
      pat:
        required: true

jobs:
  tests:
    runs-on: windows-latest
    if: ${{ inputs.tests == 'true' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          token: ${{ secrets.pat }}

      - name: Setup Java
        if: ${{ inputs.stack == 'JAVA SPRINGBOOT' || inputs.stack == 'JAVA MAVEN MULTIMODULE' }}
        uses: actions/setup-java@v2
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "8"

      - name: Test Java Spring Boot Application
        if: inputs.stack == 'JAVA SPRINGBOOT'
        run: |
          echo "Running tests from JAVA SPRINGBOOT"
          mvn clean install -DskipTests=false

      - name: Test JAVA MAVEN MULTIMODULE Application
        if: inputs.stack == 'JAVA MAVEN MULTIMODULE'
        run: |
          echo "Running tests from JAVA MAVEN MULTIMODULE"
          mvn clean install -DskipTests=false
