name: Tests

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      tests:
        type: string
        required: true
  #  secrets:
  #    token:
  #      required: true

jobs:
  ###############################################################################

  tests_java_spring:
    runs-on: ubuntu-latest
    if: ${{ inputs.tests == 'true' && inputs.stack == 'JAVA SPRINGBOOT' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ secrets.MY_PAT }}

      #its possible to use a shell script to run the tests
      - run: |
          echo "Running tests from JAVA SPRINGBOOT"
          ls -la

  ###############################################################################

  tests_java_quarkus:
    runs-on: ubuntu-latest
    if: ${{ inputs.tests == 'true' && inputs.stack == 'JAVA QUARKUS' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ github.event.inputs.repo }}
          token: ${{ secrets.my_pat }}

      #its possible to use a shell script to run the tests
      - run: |
          echo "Running build from JAVA QUARKUS"
          ls -la

###############################################################################
