name: Tests

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      tests:
        type: string
        required: true
      repo_owner:
        type: string
        required: true
      repo_name:
        type: string
        required: true
    secrets:
      pat:
        required: true

jobs:
  # JAVA SPRINGBOOT STACK

  tests_java_spring:
    runs-on: windows-latest
    if: ${{ inputs.tests == 'true' && inputs.stack == 'JAVA SPRINGBOOT' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          token: ${{ secrets.pat }}

      #its possible to use a shell script to run the tests
      - run: |
          echo "Running tests from JAVA SPRINGBOOT"
          dir

  # JAVA MAVEN STACK

  tests_java_maven:
    runs-on: windows-latest
    if: ${{ inputs.tests == 'true' && inputs.stack == 'JAVA MAVEN' }}
    steps:
      #Its needed to check out the target repo in every separeted job
      - name: Check out target repo
        uses: actions/checkout@master
        with:
          repository: ${{ inputs.repo_owner }}/${{ inputs.repo_name }}
          token: ${{ secrets.pat }}

      #its possible to use a shell script to run the tests
      - run: |
          echo "Running tests from JAVA MAVEN"
          dir
