name: TESTS

on:
  workflow_call:
    inputs:
      stack:
        type: string
        required: true
      tests:
        type: string
        required: true
  #  secrets:
  #    token:
  #      required: true

jobs:
  test_java_spring:
    runs-on: ubuntu-latest
    if: ${{ inputs.tests == 'true' && inputs.stack == 'JAVA SPRINGBOOT' }}
    steps:
      - run: echo "Running tests from JAVA SPRINGBOOT"

  test_java_quarkus:
    runs-on: ubuntu-latest
    if: ${{ inputs.tests == 'true' && inputs.stack == 'JAVA QUARKUS' }}
    steps:
      - run: echo "Running tests from JAVA QUARKUS"
